# ChefBoost is a lightweight decision tree framework for Python with categorical feature support

# It handles decision tree algorithms: ID3, C4.5, CART, CHAID and regression tree

#

In [4]:
pip install chefboost

Requirement already satisfied: chefboost in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (0.0.17)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas>=0.22.0 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from chefboost) (1.3.5)
Requirement already satisfied: tqdm>=4.30.0 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from chefboost) (4.64.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from chefboost) (1.21.4)
Requirement already satisfied: psutil>=5.4.3 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from chefboost) (5.9.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from pandas>=0.22.0->chefboost) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from pandas>=0.22.0->chefboost) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.22.0->chefboost) (1.15.0)
Requirement already satisfied: colorama in c:\users\saranya\appdata\local\programs\python\python38\lib\site-packages (from tqdm>=4.30.0->chefboost) (0.4.4)

WARNING: You are using pip version 21.1.3; however, version 22.1.2 is available.
You should consider upgrading via the 'c:\users\saranya\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

In [2]:
from chefboost import Chefboost as chef

In [3]:
import pandas as pd

df = pd.read_csv("mammals.csv")

In [4]:
df

,species,body_wt,brain_wt,non_dreaming,dreaming,total_sleep,life_span,gestation,predation,exposure,danger
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4
...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1

In [9]:
config = {'algorithm': 'C4.5'}
model = chef.fit(df, config = config, target_label = 'danger')

[INFO]:  4 CPU cores will be allocated in parallel running
WARNING: You set the algorithm to  C4.5  but the Decision column of your data set has non-object type.
That's why, the algorithm is set to Regression to handle the data set.
Regression  tree is going to be built...
-------------------------
finished in  4.590053081512451  seconds
-------------------------
Evaluate  train set
-------------------------
MAE:  0.0
MSE:  0.0
RMSE:  0.0
RAE:  0.0
RRSE:  0.0
Mean:  2.6129032258064515
MAE / Mean:  0.0 %
RMSE / Mean:  0.0 %

In [10]:
df

,species,body_wt,brain_wt,non_dreaming,dreaming,total_sleep,life_span,gestation,predation,exposure,danger
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4
...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1

In [13]:
prediction = chef.predict(model, param = ['Yellow-belliedmarmot',	4.050,	17.0,	'NaN',	'NaN',	'NaN',	13.0,	38.0,	3,	1,	1])

In [14]:
prediction

1